on:
  pull_request:
      branches:
      - main
  push:
    branches:
    - main
jobs:
  render:
    name: deploy to render
    runs-on: ubuntu-18.04
    environment: 
      name: Preview
      url: ${{nitj.onrender.com}}
    permissions:
      contents : read
    
    
